jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode12
branches:
  only:
  - /.*/
language: c
addons:
  apt:
    packages:
      - libzmq3-dev
      - bubblewrap
  homebrew:
    packages: zeromq
script: bash -ex .travis-ci.sh
env:
  matrix:
    - OCAML_VERSION=4.07.1
before_deploy: bash -ex .deploy.sh
deploy:
  provider: releases
  file_glob: true # allows shorthand for uploading multiple files
  file: kind2* # files to upload, relative to the Travis worker's working directory
  tag_name: nightly # name of the tag to associate the release with
  skip_cleanup: true # required to prevent Travis from discarding the binaries
  on:
    all_branches: true
    condition: "$TRAVIS_EVENT_TYPE = cron && $TRAVIS_REPO_SLUG = kind2-mc/kind2"
  prerelease: true
  name: "nightly"
  body: "nightly build" # doesn't work as of 1/24/20, see https://github.com/travis-ci/dpl/issues/155
  overwrite: true
  api_key: $API_KEY
